set=set()
n = input("enter a number :")
set.add(int(n))
n = input("enter a number :")
set.add(int(n))
n = input("enter a number :")
set.add(int(n))
n = input("enter a number :")
set.add(int(n))
n = input("enter a number :")
set.add(int(n))
n = input("enter a number :")
set.add(int(n))
n = input("enter a number :")
set.add(int(n))
n = input("enter a number :")
set.add(int(n))

print(set)